apiVersion: v1
kind: Secret
metadata:
    name: myapp-dev-db-master
    namespace: infra
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Gkqd12pN90wycgdNiVYs8bIbByqnuMCrbtLozdT/928itGMZ7UGWEg==,iv:qcklVCwm6lDYKO7mBFVvQqbpYtV8ye/uzqmhIo8NBy0=,tag:wWoGaxRfckYpCoEB4sl8rA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cy8yZ2FtZWUwemMzbUpE
            UHI1NFZJVkM5WFpLL2FTSm9KNmZBcms1UkNVCmtlbTBKRGVWbllQK05kalE2SHRx
            VlBkTDFwd3l0dHNmZklvY0ZncXBpRDgKLS0tIE9tK29odHhuOG83UVl5SVNkWEdY
            UmxoNGZnSUhaYlNzZE53M25GWFBUOHMKZkdekFE1kkB7dTIQB3UC1iNCPnydbieJ
            czHKJFciW/k1VlmM+KuIwSwK8zQ+VV9kipvFL0gXdcDg6ATslChK+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t7pujmuedmqnuy6ml4msuzamrv40ja5jyy9h2vwwrpg2xcwkc5esngtz7u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T16:04:08Z"
    mac: ENC[AES256_GCM,data:/2hyS7TCiWd/NpylmyxEqKDw3pGQ0Pl5iFkM8mFCz6ro5fvbq9/+68A6R1vZ2nyrY527h6J0JrvYgpDbyq7yRy7xJgdhNNfAYeLuBFHRkXVUmKaR1CHBtW0kHUTUyFfE7TUwRYMM1rXMRJDiEOj/D2EVv1I8htag+c07rnvMPLI=,iv:rr2ozjkBJlEskgoAKm6rThYaUP5buVXZMZHhI9JRGTA=,tag:cMTl8ywJ9EGXldNbtiiDiw==,type:str]
    version: 3.13.3
